[build]
    command = "yarn build:lambda"
    functions = "build-lambda"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    force = false

[dev]
    port = 42069
    targetPort = 3000