[tool.poetry]
name = "infrastructure"
version = "0.1.0"
description = ""
authors = ["David Ng <david.ng.dev@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pulumi = "^3.13.2"
pulumi-gcp = "^5.20.0"
pulumi-docker = "^3.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
