[tool.poetry]
name = "http-api"
version = "0.1.0"
description = ""
authors = ["David Ng <david.ng.dev@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = {extras = ["all"], version = "^0.68.1"}
python-dotenv = "^0.19.0"
httpx = {version = "^0.19.0"}

[tool.poetry.dev-dependencies]
pylint = "^2.11.1"
pytest = "^6.2.5"
black = "^21.9b0"
ipython = "^7.28.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"