name: Test workspace

on:
  push:
    branches:
      - development
      - master
    paths:
      - '!systems/**'
  pull_request:
    paths:
      - '!systems/**'
env:
  CI: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - run: bash ./scripts/setup.sh
      - run: bash ./scripts/lint.sh